
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Scanner;

class Test{
    public static void main(String[] arg){
//        System.out.println("Hello world!");
//        int x=5;
//        int y = 9;
//        int z=x*y;
//        float xx=5.5f;
//        double xxx=5.5555;
//        String a="Ahmed";
//        char aa='a';
//        boolean b=true;
//        int q,c;
//        q=3;
//        var qq=3;
//       final var pi=3.14f;// is constant
//        // change pi=4; it's possible
//        System.out.println(z);
//        // concatenate and new line
//        System.out.println(a+" "+"Mohamed"+" Mahmoud "+"\nnew line");
//        //Casting
//        float g=10.5f;
//        int gg = 0;
//        gg=(int)g;
//        System.out.println(gg);
//        String num="100";
//        int number=Integer.parseInt(num);
//        System.out.println(number);
//        System.out.println(num+5);
//        System.out.println(number+5);
//        // Take input from user
//        System.out.print("Enter your Name: ");
//        String s=new Scanner(System.in).nextLine();
//        System.out.println("Name: "+s);
//        //small app callc age
//        System.out.print("Enter your birth date: ");
//        int Bdate=new Scanner(System.in).nextInt();
//        int currentyear= Calendar.getInstance().get(Calendar.YEAR);
//        LocalDate currentyear1= LocalDate.now();
//        LocalTime currenttime=LocalTime.now();
//        var currenttime1=LocalTime.now();
//        int age=currentyear-Bdate;
//        System.out.println("your age i*96s: "+age);
//        System.out.println("current year: "+currentyear);
//        System.out.println("current time: "+currenttime);
//        System.out.println("current time: "+currenttime1);
//        //some operations
//        System.out.println(12/5);//2
//        System.out.println(12.0/5.0);//2.4
//        System.out.println(12%5);//2
//        System.out.println(12<=5 && 2!=2);
//        System.out.println("Enter Name: ");
//        String Name= new Scanner(System.in).nextLine();
//        System.out.println("Enter age: ");
//        int age1= new Scanner(System.in).nextInt();
//        // if statement
//        if(age1>=20){
//            System.out.println(Name+" has "+age1+" years");
//        }else {
//            System.out.println(Name+" aren't adult");
//        }
//        int var=5;
//        if (var==5){
//            var++;
//            System.out.println(var);
//        }else if(var>5){
//            System.out.println(var);
//        }else System.out.println(var);
//        int give_value_inline=(6>2)?5:6;//5
//        System.out.println(give_value_inline);
//        //switch
//        System.out.print("Enter X: ");
//        int X=new Scanner(System.in).nextInt();
//        switch (X){
//            case 0:{System.out.println("case 1: ");break;}
//            case 1:{System.out.println("case 2: ");break;}
//            case 2:{System.out.println("case 3: ");break;}
//            default:System.out.println("case "+(X-1)+": ");break;
//        }
//        System.out.println("Enter first number: ");
//        int num1=new Scanner(System.in).nextInt();
//        System.out.println("Enter second number: ");
//        int num2=new Scanner(System.in).nextInt();
//        System.out.println("Enter operation: ");
//        String op=new Scanner(System.in).nextLine();
//        int result=0;
//        switch (op) {
//            case "+" : result = num1 + num2;break;
//            case "-" : result = num1 - num2;break;
//            case "*" : result = num1 * num2;break;
//            case "/" : result = num1 / num2;break;
//            default : System.out.println("op is incorrect: ");break;
//        }
//        System.out.println("result: "+result);
        // Enhanced switch
//        System.out.println("Enter first number: ");
//        int num1=new Scanner(System.in).nextInt();
//        System.out.println("Enter second number: ");
//        int num2=new Scanner(System.in).nextInt();
//        System.out.println("Enter operation: ");
//        String op=new Scanner(System.in).nextLine();
//        int result=0;
//        switch (op) {
//            case "+" -> result = num1 + num2;
//            case "-" -> result = num1 - num2;
//            case "*" -> result = num1 * num2;
//            case "/" -> result = num1 / num2;
//            default -> System.out.println("op is incorrect: ");
//        }
//        System.out.println("result: "+result);
        //for loops
        // While
//        System.out.print("Enter number: ");
//        int xy=new Scanner(System.in).nextInt();
//        while(xy<=5){
//            System.out.println(xy);
//            xy++;
//        }
//        System.out.println("///////////////////////////////////////");
//        do{
//            System.out.println(xy);
//            xy--;
//        }while (xy>=5);
//        System.out.println("///////////////////////////////////////");
//        //for loop
//        for (int zz=0;zz<5;zz++){
//            System.out.println(zz);
//        }
////        //جدول الضرب
////       for (int x=0;x<=10;x++){
////           for (int y=0;y<=10;y++){
////               System.out.println(x+"*"+y+"="+x*y);
////           }
////       }
////        // Control Statements break; continue;
////        mohamed:
////        for (int x=0;x<=10;x++){
////            ahmed:
////           for (int y=0;y<=10;y++){
////               if (y==3)break mohamed;
////               System.out.println(x+"*"+y+"="+x*y);
////           }
////       }
////        0*0=0
////        0*1=0
////        0*2=0
        //try catch
//        while (true){
//            try {
//                System.out.print("Enter your age: ");
//                int age=new Scanner(System.in).nextInt();
//                System.out.println("your age is: "+age);
//                break;
//            } catch (Exception e) {
//                System.out.println("Wrong! ");
//
//            }
//        }

    }
}